---
- name: Create and start Pushgateway service
  community.docker.docker_compose_v2:
    project_name: sudowatch
    definition:
      version: '2'


      networks:
        sudowatch_watch-net:
          external: true

      services:

        pushgateway:
          image: prom/pushgateway:v1.3.1
          container_name: pushgateway
          restart: unless-stopped
          expose:
            - 9091
          networks:
            - sudowatch_watch-net
          labels:
            container_group: "sudowatch"
  register: output
  when: enable_pushgateway

# - name: Verify if the container is up
#   assert:
#     that:
#       - "pushgateway.pushgateway.state.running"
#   when: enable_pushgateway
